//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESUNTest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarriageInfo
    {
        public string statistic_yyy { get; set; }
        public string according { get; set; }
        public string site_id { get; set; }
        public string marriage_type { get; set; }
        public string female_age { get; set; }
        public string male_age { get; set; }
        public string marry_pair { get; set; }
    }
}
